name: Deploy to Firebase Hosting

# Se dispara en cada push a main (ajusta tu rama si fuera otra)
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - uses: actions/checkout@v4

      # 2. Configurar Node.js (opcionalmente fija versión)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Build de producción
      - name: Build
        run: npm run build

      # 5. Deploy a Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EDDEVIOS_PORTFOLIO_2025 }}"
          channelId: live    # 'live' publica en producción; puedes usar preview channels
